import = [
    "~/.config/alacritty/alacritty-theme/themes/gruvbox_dark.toml"
]

[colors.primary]
background = "#282828" # "#000000"
foreground = "#ebdbb2"

[colors.normal]
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[32;2u"
key = "Space"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[32;5u"
key = "Space"
mods = "Control"

[window]
opacity = 1.0 # 0.6

[font]
builtin_box_drawing = false
size                = 12

[font.bold]
family = "JetBrainsMono Nerd Font"
style  = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style  = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style  = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style  = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
key = "+"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "-"
mods = "Control"
action = "DecreaseFontSize"
