return {
	"ellisonleao/gruvbox.nvim",
	priority = 1000,
	lazy = false,
	config = function()
		require("gruvbox").setup({
			terminal_colors = true,
			undercurl = true,
			underline = true,
			bold = true,
			italic = {
				strings = true,
				emphasis = true,
				comments = true,
				operators = false,
				folds = true,
			},
			strikethrough = true,
			invert_selection = false,
			invert_signs = false,
			invert_tabline = false,
			invert_intend_guides = false,
			inverse = true,
			contrast = "hard",
			palette_overrides = {
				--[[
				light0_hard = "#f9f9f9",
				light0 = "#fbfbfb",
				light0_soft = "#f2f2f2",
				light1 = "#ebdbb2",
				light2 = "#d5c4a1",
				light3 = "#bdae93",
				light4 = "#a89984",
				bright_red = "#fb4934",
				bright_green = "#b8bb26",
				bright_yellow = "#fabd2f",
				bright_blue = "#83a598",
				bright_purple = "#d3869b",
				bright_aqua = "#8ec07c",
				bright_orange = "#fe8019",
				neutral_red = "#cc241d",
				neutral_green = "#98971a",
				neutral_yellow = "#d79921",
				neutral_blue = "#458588",
				neutral_purple = "#b16286",
				neutral_aqua = "#689d6a",
				neutral_orange = "#d65d0e",
				--]]
				bright_red = "#cc241d",
				bright_green = "#98971a",
				bright_yellow = "#d79921",
				bright_blue = "#458588",
				bright_purple = "#b16286",
				bright_aqua = "#689d6a",
				bright_orange = "#d65d0e",
			},
			overrides = {},
			dim_inactive = false,
			transparent_mode = true,
		})
		vim.cmd.colorscheme("gruvbox")
	end,
}
